"""
Code Generator Agent

For each MethodSpec, generates a complete Kaggle-ready .ipynb notebook.

Strategy: Jinja2 base template (reliable structure) + Claude fills in
the method-specific logic. This gives us:
  - Consistent output contract (metrics.json always saved)
  - Reliable imports and boilerplate
  - LLM creativity only where it's needed (model code, feature engineering)

Every generated notebook:
  1. Loads data from /kaggle/input/
  2. Applies feature engineering from MethodSpec
  3. Trains with cross-validation + Optuna hyperparameter search
  4. Saves model to /kaggle/working/model.*
  5. Saves metrics to /kaggle/working/metrics.json
  6. Saves predictions to /kaggle/working/predictions.csv

The researcher can open any notebook on Kaggle and read it â€”
everything is commented in plain English.
"""

import json
import logging
import re
from pathlib import Path

import nbformat

from agents.api_utils import LLMClient
from jinja2 import Environment, FileSystemLoader
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

from schemas import (
    ProblemSpec,
    DataHealthReport,
    MethodSpec,
    TaskType,
)

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates" / "notebooks"


def _sanitize_code_for_notebook(code: str) -> str:
    """Remove characters that would corrupt a notebook cell or its JSON encoding."""
    if not code:
        return ""
    # Strip to ASCII only â€” removes emoji and other multi-byte symbols
    code = code.encode("ascii", errors="ignore").decode("ascii")
    # Remove null bytes
    code = code.replace("\x00", "")
    # Remove control characters except newline (\n) and tab (\t)
    code = re.sub(r"[\x01-\x08\x0b\x0c\x0e-\x1f\x7f]", "", code)
    return code


def _fix_json_newlines(s: str) -> str:
    """
    Escape literal newlines/carriage returns that appear INSIDE JSON string values.

    Claude sometimes returns JSON like:
        {"code": "line1
    line2"}
    instead of:
        {"code": "line1\\nline2"}

    This breaks json.loads. We fix it by walking the string and escaping
    any bare newlines that occur while we're inside a JSON string.
    """
    result = []
    in_string = False
    escape_next = False
    for ch in s:
        if escape_next:
            result.append(ch)
            escape_next = False
        elif ch == "\\" and in_string:
            result.append(ch)
            escape_next = True
        elif ch == '"':
            in_string = not in_string
            result.append(ch)
        elif ch == "\n" and in_string:
            result.append("\\n")
        elif ch == "\r" and in_string:
            result.append("\\r")
        else:
            result.append(ch)
    return "".join(result)


# â”€â”€ Notebook template (inline â€” used before file templates are built) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

BASE_NOTEBOOK_TEMPLATE = '''\
# AutoResearch â€” {{ method.name }}
# Problem: {{ spec.plain_english_summary }}
# Generated by AutoResearch. Read, run, and modify â€” it\'s yours.

"""
WHY THIS METHOD WAS CHOSEN:
{{ method.why_chosen }}

WATCH OUT FOR:
{{ method.watch_out_for }}
"""
'''

# The standard scaffold every notebook follows
NOTEBOOK_SCAFFOLD = {
    "imports": """\
# â”€â”€ Imports â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
import os, json, warnings
import numpy as np
import pandas as pd
from pathlib import Path
warnings.filterwarnings('ignore')

# Output directory â€” everything AutoResearch needs gets saved here
OUTPUT_DIR = Path('/kaggle/working')
OUTPUT_DIR.mkdir(exist_ok=True)

print("âœ“ Imports loaded")
""",

    "load_data": """\
# â”€â”€ Load Data â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# Finding your data in the Kaggle input directory

data_path = None
for root, dirs, files in os.walk('/kaggle/input'):
    for f in files:
        if f.endswith('.csv'):
            data_path = os.path.join(root, f)
            break
    if data_path:
        break

if not data_path:
    raise FileNotFoundError(
        "No CSV file found. Make sure your dataset is attached to this kernel."
    )

df = pd.read_csv(data_path)
print(f"âœ“ Loaded data: {df.shape[0]:,} rows Ã— {df.shape[1]} columns")
print(f"  Target column: {target_col!r}")
print(df.head(3))
""",

}


# â”€â”€ System prompt for code generation â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

CODEGEN_SYSTEM_PROMPT = """\
You are the code generator for AutoResearch. Your job is to write the
method-specific Python code for a Kaggle notebook.

## What you write

You write ONLY the middle sections of the notebook:
1. Feature engineering code
2. Model training code (with cross-validation)
3. Optuna hyperparameter optimization
4. Evaluation code
5. Output saving code (metrics.json and model artifact)

The scaffold (imports, data loading, output saving) is handled separately.

## Rules

1. Use sklearn-compatible API where possible
2. Always use cross-validation (StratifiedKFold for classification, KFold for others)
3. Use Optuna for hyperparameter search (n_trials=30 for speed)
4. Save model with joblib.dump() to /kaggle/working/model.pkl
5. Compute both train AND validation metrics (to detect overfitting)
6. Comment every non-obvious step in plain English
7. Handle class imbalance with class_weight='balanced' when flagged
8. Cap training time: add early_stopping where supported
9. If missing values are present, add imputation (SimpleImputer) before modeling
10. Use train_test_split with stratify=y for classification before cross-validation

## Output format

Return a JSON object with these keys:
{
  "feature_engineering_code": "...",
  "model_training_code": "...",
  "evaluation_code": "...",
  "output_saving_code": "...",
  "additional_imports": ["import xgboost as xgb", ...]
}

Code only. No markdown, no backticks, no explanation outside the JSON.

CRITICAL: Output pure ASCII Python code only. Do NOT use any emoji, unicode symbols,
or special characters (no emojis, arrows, bullets, etc.) in print statements or
comments. Use plain ASCII only: print('Done'), print('Error'), print('Results:') etc.
"""


def build_codegen_prompt(
    spec: ProblemSpec,
    report: DataHealthReport,
    method: MethodSpec,
    error_context: str = "",
) -> str:
    """Build the prompt for generating method-specific code."""

    imbalance_note = ""
    for flag, severity, explanation in report.flags:
        if "imbalance" in flag.value.lower():
            imbalance_note = f"\nClass imbalance detected: {explanation}"
            break

    error_section = ""
    if error_context:
        error_section = f"\n## Previous Attempt Failed â€” Fix This\n\n{error_context}\n"

    # Rich data context from EDA â€” gives Claude exact file paths and column names
    data_context = f"""
## Dataset Information (from EDA â€” use these exact values)

- Train file path: {getattr(report, 'train_path', None) or '/kaggle/input/'}
- Test file path:  {getattr(report, 'test_path',  None) or '/kaggle/input/'}
- Target column:   {getattr(report, 'label_column', None) or spec.target_column or 'none'}
- All columns:     {getattr(report, 'all_columns', [])}
- Feature columns: {getattr(report, 'feature_columns', [])}
- Numeric columns: {getattr(report, 'numeric_columns', [])}
- Training rows:   {report.row_count:,}
- Column dtypes:   {json.dumps({k: v.get('dtype') for k, v in getattr(report, 'column_analysis', {}).items()}, indent=2) if getattr(report, 'column_analysis', {}) else 'see dataset'}
- Sample rows:     {json.dumps(getattr(report, 'sample_rows', [])[:2], default=str)}
- Recommendations: {report.recommendations}
- Method hints:    {report.method_hints}
"""

    diagnostics = spec.dataset_diagnostics
    diagnostics_context = "none"
    if diagnostics is not None:
        diagnostics_context = (
            f"risk_flags={diagnostics.risk_flags}; "
            f"missing_value_columns={diagnostics.missing_value_columns}; "
            f"high_cardinality_columns={diagnostics.high_cardinality_columns}; "
            f"leakage_candidates={diagnostics.leakage_candidates}; "
            f"duplicate_ratio={diagnostics.duplicate_ratio:.3f}; "
            f"class_distribution={diagnostics.class_distribution}; "
            f"recommendations={diagnostics.recommendations[:5]}"
        )

    prep = spec.data_prep
    prep_context = "none"
    if prep is not None:
        prep_context = (
            f"target={prep.target_column}; "
            f"normalize_column_names={prep.normalize_column_names}; "
            f"missing_value_columns={prep.missing_value_columns}; "
            f"high_cardinality_columns={prep.high_cardinality_columns}; "
            f"leakage_candidates={prep.leakage_candidates}; "
            f"duplicate_ratio={prep.duplicate_ratio:.3f}; "
            f"drop_duplicate_rows={prep.drop_duplicate_rows}; "
            f"impute_numeric={prep.impute_numeric}; "
            f"impute_categorical={prep.impute_categorical}; "
            f"stratify_split={prep.stratify_split}; "
            f"recommendations={prep.recommendations[:5]}"
        )

    return f"""## Method to Implement{error_section}

Name: {method.name}
Algorithm family: {method.algorithm_family}
Why chosen: {method.why_chosen}
{data_context}
## Problem Context

Task type: {spec.task_type.value}
Target column: {spec.target_column or "none"}
Primary metric: {spec.primary_metric.value}
Dataset: {report.row_count:,} rows Ã— {report.column_count} columns{imbalance_note}
Diagnostics: {diagnostics_context}
Data prep guidance: {prep_context}

## Feature Engineering Steps

{json.dumps(method.feature_engineering, indent=2)}

## Hyperparameter Search Space (for Optuna)

{json.dumps(method.hyperparam_space, indent=2)}

## Variables already defined (from scaffold)

- `df`: pandas DataFrame with all data
- `target_col`: string name of target column ('{spec.target_column or ""}')
- `OUTPUT_DIR`: Path to /kaggle/working

## Your task

Write the feature engineering, model training (with CV + Optuna), and
evaluation code, plus output-saving code. The code must define these variables at the end:
- `primary_metric_value`: float
- `primary_metric_name`: str = '{spec.primary_metric.value}'
- `all_metrics`: dict
- `train_metric`: float
- `val_metric`: float
- `runtime_seconds`: float
- `method_name`: str = '{method.name}'

Respond with a JSON object with exactly these keys:
{{
  "feature_engineering_code": "# python code here as a single string",
  "model_training_code": "# python code here as a single string",
  "evaluation_code": "# python code here as a single string",
  "output_saving_code": "# python code that saves metrics/model outputs",
  "additional_imports": ["import torch", "import torchvision"]
}}

RULES:
- All code goes inside JSON string values
- Use \\n for newlines inside the JSON strings
- NO emoji or unicode -- ASCII only
- NO markdown fences around the JSON
- The entire response must be parseable by json.loads()
- Apply imputation when missing values are present
- Use stratified train_test_split for classification
- output_saving_code MUST save /kaggle/working/metrics.json and a model artifact
"""


class CodeGenAgent:
    """
    The Code Generation Agent.

    Takes a MethodSpec and generates a complete, runnable Kaggle notebook.
    Uses Jinja2 for the scaffold + Claude for method-specific code.

    Usage:
        agent = CodeGenAgent(api_key="...")
        notebook = agent.generate(spec, report, method)
        # Returns nbformat.NotebookNode ready to push to Kaggle
    """

    def __init__(self, llm: LLMClient, verbose: bool = True):
        self.llm     = llm
        self.verbose = verbose

    def generate(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        error_context: str = "",
    ) -> nbformat.NotebookNode:
        """
        Generate a complete Kaggle notebook for this method.

        Args:
            spec:   ProblemSpec
            report: DataHealthReport
            method: MethodSpec to implement

        Returns:
            nbformat.NotebookNode ready to push to Kaggle
        """
        if self.verbose:
            print(f"  ðŸ“ Generating notebook for: {method.name}")

        # 1. Generate method-specific code via Claude
        method_code = self._generate_method_code(spec, report, method, error_context)

        # 2. Assemble the full notebook
        notebook = self._assemble_notebook(spec, method, method_code)

        # 3. Lint check
        issues = self._lint_notebook(notebook)
        if issues:
            logger.warning(f"Lint issues in {method.name} notebook: {issues}")
            # One-shot self-repair pass with explicit lint feedback.
            repair_context = (
                (error_context + "\n\n" if error_context else "")
                + "Notebook lint issues to fix:\n- "
                + "\n- ".join(issues)
            )
            repaired_code = self._generate_method_code_via_sections(
                spec=spec,
                report=report,
                method=method,
                error_context=repair_context,
            )
            notebook = self._assemble_notebook(spec, method, repaired_code)
            issues = self._lint_notebook(notebook)
            if issues:
                logger.warning(f"Lint issues remain in {method.name} after repair: {issues}")

        if self.verbose:
            cells = len(notebook.cells)
            print(f"  âœ“ Notebook ready ({cells} cells)")

        return notebook

    def generate_all(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        methods: list[MethodSpec],
    ) -> list[tuple[MethodSpec, nbformat.NotebookNode]]:
        """Generate notebooks for all methods."""
        results = []
        for method in methods:
            try:
                nb = self.generate(spec, report, method)
                results.append((method, nb))
            except Exception as e:
                logger.error(f"Failed to generate notebook for {method.name}: {e}")
                raise RuntimeError(
                    f"AutoResearch couldn't generate the code for '{method.name}'.\n"
                    f"Technical detail: {e}"
                )
        return results

    def _generate_method_code(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        error_context: str = "",
    ) -> dict:
        """Ask Claude for the method-specific code sections."""
        # GPU methods (CV/NLP/large NN) produce much longer code â€” use separate calls
        # to avoid truncation and JSON-wrapping problems.
        if method.requires_gpu:
            return self._generate_method_code_gpu(spec, report, method, error_context)

        raw = self.llm.create(
            system=CODEGEN_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": build_codegen_prompt(spec, report, method, error_context)}],
            max_tokens=3000,
            verbose=self.verbose,
        )
        raw = _sanitize_code_for_notebook(raw)  # strip emoji/non-ASCII before JSON parsing
        try:
            # Strip markdown fences and extract the outermost JSON object
            clean = re.sub(r"```(?:json)?|```", "", raw).strip()
            brace_start = clean.find("{")
            brace_end   = clean.rfind("}")
            if brace_start != -1 and brace_end != -1:
                clean = clean[brace_start:brace_end + 1]
            parsed = json.loads(clean)
            # Sanitize all code fields so control characters don't corrupt the notebook
            for key in ("feature_engineering_code", "model_training_code", "evaluation_code", "output_saving_code"):
                if key in parsed:
                    parsed[key] = _sanitize_code_for_notebook(parsed[key])
            return self._ensure_required_sections(spec, report, method, parsed, error_context)
        except json.JSONDecodeError:
            # Claude returned JSON with literal newlines inside string values â€” fix and retry
            try:
                fixed = _fix_json_newlines(clean)
                parsed = json.loads(fixed)
                for key in ("feature_engineering_code", "model_training_code", "evaluation_code", "output_saving_code"):
                    if key in parsed:
                        parsed[key] = _sanitize_code_for_notebook(parsed[key])
                logger.info(f"Parsed codegen response for {method.name} after newline fix")
                return self._ensure_required_sections(spec, report, method, parsed, error_context)
            except json.JSONDecodeError:
                pass
            # Fallback: generate section-by-section via LLM (no hardcoded experiment logic).
            logger.warning(f"Could not parse codegen response for {method.name}, using LLM section fallback")
            logger.warning(f"Raw response preview: {repr(raw[:300])}")
            return self._generate_method_code_via_sections(spec, report, method, error_context)

    # â”€â”€ Section prompts for GPU split-call path â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    _SECTION_PROMPTS = {
        "feature_engineering": (
            "Write ONLY the feature engineering code in plain Python (no JSON, no markdown). "
            "Input variables available: df, target_col. "
            "Output should prepare X_train, X_val, X_test, y_train, y_val ready for the model."
        ),
        "model_training": (
            "Write ONLY the model training code in plain Python (no JSON, no markdown). "
            "Input: X_train, X_val, X_test, y_train, y_val from feature engineering. "
            "Include cross-validation and Optuna hyperparameter tuning (n_trials=20). "
            "Set these variables at the end: primary_metric_value (float), "
            "primary_metric_name (str), train_metric (float), val_metric (float), "
            "all_metrics (dict), runtime_seconds (float), method_name (str)."
        ),
        "evaluation": (
            "Write ONLY the evaluation code in plain Python (no JSON, no markdown). "
            "Variables available: primary_metric_value, primary_metric_name, "
            "train_metric, val_metric, all_metrics, runtime_seconds, method_name."
        ),
        "output_saving": (
            "Write ONLY the output-saving code in plain Python (no JSON, no markdown). "
            "Must save /kaggle/working/metrics.json and save the model to "
            "/kaggle/working/model.pkl (or .pt for PyTorch). "
            "Variables available: primary_metric_value, primary_metric_name, "
            "train_metric, val_metric, all_metrics, runtime_seconds, method_name, OUTPUT_DIR."
        ),
        "imports": (
            "List ONLY the import statements needed for this method, one per line, "
            "plain Python. No explanations, no markdown."
        ),
    }

    def _generate_section(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        section: str,
        error_context: str = "",
    ) -> str:
        """Generate a single code section via a dedicated API call (used for GPU methods)."""
        section_instruction = self._SECTION_PROMPTS[section]
        error_note = f"\nPrevious attempt failed â€” fix this:\n{error_context}\n" if error_context else ""
        diagnostics = spec.dataset_diagnostics
        prep = spec.data_prep
        context_note = (
            f"Rows={report.row_count}, Cols={report.column_count}, "
            f"Target={spec.target_column or report.label_column or 'none'}, "
            f"Feature cols={report.feature_columns[:12]}, "
            f"Numeric cols={report.numeric_columns[:12]}, "
            f"Method family={method.algorithm_family}, "
            f"Method hyperparams={method.hyperparam_space}, "
            f"Diagnostics flags={diagnostics.risk_flags if diagnostics else []}, "
            f"Prep notes={prep.recommendations[:3] if prep else []}"
        )

        response_text = self.llm.create(
            system=(
                "You are an expert ML engineer. Write clean, working Python code only. "
                "No explanations, no markdown, no JSON, no emoji. Pure Python code."
            ),
            messages=[{
                "role": "user",
                "content": (
                    f"Method: {method.name}\n"
                    f"Task: {spec.plain_english_summary}\n"
                    f"Target column: {spec.target_column or 'none'}\n"
                    f"Primary metric: {spec.primary_metric.value}\n"
                    f"Data context: {context_note}\n"
                    f"{error_note}\n"
                    f"{section_instruction}"
                ),
            }],
            max_tokens=4000,
            verbose=self.verbose,
        )
        raw = re.sub(r"```(?:python)?\s*", "", response_text).replace("```", "").strip()
        return _sanitize_code_for_notebook(raw)

    def _generate_method_code_gpu(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        error_context: str = "",
    ) -> dict:
        """
        GPU methods (CV, NLP, large NN) produce code that is too long to fit
        reliably in a single JSON-wrapped response. Use separate API calls per
        section to avoid truncation and JSON-parsing failures.
        """
        if self.verbose:
            print(f"    (GPU method â€” generating sections separately)")
        return {
            "additional_imports":       self._generate_section(spec, report, method, "imports",              error_context),
            "feature_engineering_code": self._generate_section(spec, report, method, "feature_engineering",  error_context),
            "model_training_code":      self._generate_section(spec, report, method, "model_training",       error_context),
            "evaluation_code":          self._generate_section(spec, report, method, "evaluation",            error_context),
            "output_saving_code":       self._generate_section(spec, report, method, "output_saving",         error_context),
        }

    def _generate_method_code_via_sections(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        error_context: str = "",
    ) -> dict:
        """Generate all sections independently via LLM (used as robust fallback)."""
        return {
            "additional_imports":       self._generate_section(spec, report, method, "imports",              error_context),
            "feature_engineering_code": self._generate_section(spec, report, method, "feature_engineering",  error_context),
            "model_training_code":      self._generate_section(spec, report, method, "model_training",       error_context),
            "evaluation_code":          self._generate_section(spec, report, method, "evaluation",            error_context),
            "output_saving_code":       self._generate_section(spec, report, method, "output_saving",         error_context),
        }

    def _ensure_required_sections(
        self,
        spec: ProblemSpec,
        report: DataHealthReport,
        method: MethodSpec,
        parsed: dict,
        error_context: str = "",
    ) -> dict:
        """
        Fill missing required sections by asking the LLM, instead of using hardcoded placeholders.
        """
        result = dict(parsed)
        required_sections = {
            "feature_engineering_code": "feature_engineering",
            "model_training_code": "model_training",
            "evaluation_code": "evaluation",
            "output_saving_code": "output_saving",
        }
        for field, section in required_sections.items():
            if not str(result.get(field, "")).strip():
                logger.warning(f"Missing '{field}' for {method.name}; generating via section fallback")
                result[field] = self._generate_section(spec, report, method, section, error_context)
        result.setdefault("additional_imports", [])
        return result

    def _assemble_notebook(
        self,
        spec: ProblemSpec,
        method: MethodSpec,
        method_code: dict,
    ) -> nbformat.NotebookNode:
        """
        Assemble the full notebook cell-by-cell using nbformat.

        We always use manual assembly (never the Jinja2 template) because
        templates that render to .ipynb JSON with embedded Python code are
        inherently fragile â€” literal newlines inside template variables break
        json.loads(). nbformat's new_code_cell() handles all escaping correctly.
        """
        return self._assemble_manual(spec, method, method_code)

    def _assemble_from_template(
        self,
        spec: ProblemSpec,
        method: MethodSpec,
        method_code: dict,
        template_path: Path,
    ) -> nbformat.NotebookNode:
        """
        Render the Jinja2 .ipynb.j2 template, injecting:
          - method metadata (name, why_chosen, watch_out_for)
          - problem spec (target_col, primary_metric, task_type)
          - Claude's generated code into {{ model_training_code }} etc.
        Then parse the rendered JSON as a notebook.
        """
        env = Environment(
            loader=FileSystemLoader(str(TEMPLATES_DIR)),
            # Keep newlines inside code blocks intact
            keep_trailing_newline=True,
            # Don't escape HTML in code
            autoescape=False,
        )
        template = env.get_template(template_path.name)

        # Detect class imbalance from flags in DataHealthReport if available
        # (passed through method.hyperparam_space as a hint if set)
        has_imbalance = "class_weight" in str(method_code.get("model_training_code", ""))

        rendered_json = template.render(
            # Method metadata
            method_name=method.name,
            why_chosen=method.why_chosen,
            watch_out_for=method.watch_out_for,
            algorithm_family=method.algorithm_family,
            feature_engineering=method.feature_engineering,
            additional_imports=method_code.get("additional_imports", []),

            # Problem spec
            target_col=spec.target_column or "",
            primary_metric=spec.primary_metric.value,
            task_type=spec.task_type.value,
            has_class_imbalance="True" if has_imbalance else "False",

            # Claude's generated code (injected into template slots)
            model_training_code=method_code.get("model_training_code", "# model training code"),
            evaluation_code=method_code.get("evaluation_code", "# evaluation code"),

            # Sensible defaults
            n_folds=5,
            n_trials=30,
            img_size=224,
            batch_size=32,
            num_epochs=15,
            forecast_horizon=30,

            # Text/CV extras (auto-detected in notebook if wrong)
            text_col="text",
            date_col="date",
        )

        try:
            nb_dict = json.loads(rendered_json)
            nb = nbformat.from_dict(nb_dict)
            nbformat.validate(nb)
            return nb
        except (json.JSONDecodeError, nbformat.ValidationError) as e:
            logger.warning(f"Template render produced invalid notebook: {e} â€” falling back")
            return self._assemble_manual(spec, method, method_code)

    def _assemble_manual(
        self,
        spec: ProblemSpec,
        method: MethodSpec,
        method_code: dict,
    ) -> nbformat.NotebookNode:
        """Fallback: build notebook cell-by-cell without a template."""
        cells = []

        cells.append(new_markdown_cell(
            f"# {method.name}\n\n"
            f"**Problem:** {spec.plain_english_summary}\n\n"
            f"**Why this method:** {method.why_chosen}\n\n"
            f"**Watch out for:** {method.watch_out_for}\n\n"
            f"> Generated by AutoResearch. Read it, run it, modify it â€” it's yours."
        ))

        raw_imports = method_code.get("additional_imports", [])
        # GPU path returns a plain string; CPU path returns a list
        extra_imports = raw_imports if isinstance(raw_imports, str) else "\n".join(raw_imports)
        cells.append(new_code_cell(
            NOTEBOOK_SCAFFOLD["imports"]
            + ("\n# Method-specific imports\n" + extra_imports if extra_imports else "")
        ))

        cells.append(new_code_cell(
            f"target_col = {repr(spec.target_column or '')}\n"
            f"task_type  = {repr(spec.task_type.value)}\n"
            f"metric     = {repr(spec.primary_metric.value)}\n"
            f"print(f'Target: {{target_col}} | Task: {{task_type}} | Metric: {{metric}}')"
        ))

        cells.append(new_code_cell(NOTEBOOK_SCAFFOLD["load_data"]))
        cells.append(new_markdown_cell("## Feature Engineering"))
        cells.append(new_code_cell(method_code.get("feature_engineering_code", "")))
        cells.append(new_markdown_cell("## Model Training"))
        cells.append(new_code_cell(method_code.get("model_training_code", "")))
        cells.append(new_markdown_cell("## Results"))
        cells.append(new_code_cell(method_code.get("evaluation_code", "")))
        cells.append(new_markdown_cell("## Save Outputs"))
        cells.append(new_code_cell(method_code.get("output_saving_code", "")))

        nb = new_notebook(cells=cells)
        nb.metadata["kernelspec"] = {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        }
        return nb

    def _lint_notebook(self, notebook: nbformat.NotebookNode) -> list[str]:
        """Basic lint checks on the generated notebook."""
        issues = []
        full_code = "\n".join(
            cell.source for cell in notebook.cells
            if cell.cell_type == "code"
        )

        required = ["metrics.json", "primary_metric_value", "val_metric", "train_metric"]
        for r in required:
            if r not in full_code:
                issues.append(f"Missing required output: {r}")
        if "model.pkl" not in full_code and ".pt" not in full_code and ".joblib" not in full_code:
            issues.append("Missing required output: model artifact save")

        return issues
