"""Pydantic schemas for the Interview Research pipeline."""

from typing import Literal, Optional
from pydantic import BaseModel, Field


class InterviewPipelineInput(BaseModel):
    jd_text: str                                    # full job description text
    profile_text: Optional[str] = None             # if None, loaded from ProfileStore
    company_name: str
    role_title: str
    depth: Literal["quick", "full"] = "full"        # quick skips live company research


class FitVerdict(BaseModel):
    overall_score: float                            # 0–10; 7+ = worth pursuing
    match_strengths: list[str] = Field(default_factory=list)
    gaps: list[str] = Field(default_factory=list)
    deal_breakers: list[str] = Field(default_factory=list)
    recommendation: Literal["strong_fit", "worth_pursuing", "stretch", "not_recommended"]
    summary: str                                    # 2–3 sentences: biggest strength + biggest risk


class CompanyProfile(BaseModel):
    culture_summary: str
    interview_style: str                            # e.g. "behavioural-heavy", "case + system design"
    known_values: list[str] = Field(default_factory=list)
    prep_priorities: list[str] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)


class QuestionSet(BaseModel):
    behavioural: list[str] = Field(default_factory=list)
    technical: list[str] = Field(default_factory=list)
    culture_fit: list[str] = Field(default_factory=list)
    curveball: list[str] = Field(default_factory=list)


class STARAnswer(BaseModel):
    question: str
    situation: str
    task: str
    action: str
    result: str                                     # must include a specific number or outcome
    tailoring_note: str                             # why this answer lands for this company


class AnswerSet(BaseModel):
    answers: list[STARAnswer] = Field(default_factory=list)


class TailoredResume(BaseModel):
    """
    A version of the candidate's resume rewritten to target a specific JD.

    Generated by ResumeWriterAgent (Node 5) from the master profile + FitVerdict.
    The full_resume_md field is the submission-ready artefact; the other fields
    are component outputs that can be selectively displayed or edited.
    """
    target_role: str
    target_company: str
    summary: str                                    # rewritten professional summary for this JD
    highlighted_skills: list[str]                   # skills filtered + ordered by JD relevance
    experience_bullets: list[str]                   # top achievement bullets reframed for this role
    cover_letter_opener: str                        # opening paragraph of a strong cover letter
    full_resume_md: str                             # complete tailored resume in Markdown
    tailoring_notes: list[str]                      # what was changed and why (transparency)


class InterviewPrepBrief(BaseModel):
    role_title: str
    company_name: str
    as_of_date: str
    fit: FitVerdict
    company: CompanyProfile
    questions: QuestionSet
    answers: AnswerSet
    top_3_priorities: list[str]                     # the 3 highest-leverage things to nail
    tailored_resume: Optional[TailoredResume] = None  # present when depth="full"
